[custom_review.instructions]
# Custom instructions for documentation reviews
pr_custom_review_instructions = """
# Documentation Review Guidelines for Awesome Agents MD
- Ensure content follows repository standards (see CONTRIBUTING.md)
- Check for clear, concise writing with proper grammar
- Verify markdown formatting (tables, code blocks, headings)
- Validate YAML files (.yaml) for proper syntax and structure
- Confirm consistent naming (lowercase with hyphens, no underscores)
- Check folder structure adheres to README.md hierarchy
- Look for broken internal/external links
- Ensure content is relevant to software development guides
- Review for accessibility (clear headings, alt text if images)
- Validate that new agents are properly added to index.yaml
"""

[pr_reviewer]
pr_reviewer.enabled = true
customization_keywords = ["documentation", "guide", "domain", "framework", "workflow", "readme", "yaml", "markdown"]

[pr_questions]
# Disable code-specific questions
pr_questions.enabled = false

[pr_reviewer.pr_reviewer]
extra_instructions = """
Focus documentation-specific review on:
- Content clarity and technical accuracy
- Markdown table and list formatting
- YAML syntax validation
- Cross-references between guides
- Consistency with existing documentation style
- Relevance to repository categories (domains, frameworks, etc.)
- Compliance with contribution guidelines
"""

[pr_templates.docs]
template = """
Review for MD Files:
- Title clarity and relevance to repository structure
- Proper markdown formatting (headings, lists, code blocks, tables)
- Grammar and writing clarity
- Technical accuracy and completeness
- Consistency with existing documentation style
- Cross-references and internal/external links
- Accessibility considerations (alt text, clear descriptions)
- Adherence to contribution guidelines in CONTRIBUTING.md
- Relevance to software development domains/frameworks
- Appropriate file location within repository folder structure
- Relevancy of content to agent guides (if applicable)
"""

[pr_templates.yaml]
template = """
Validate YAML Files:
- YAML syntax correctness and proper formatting
- Schema compliance for agents or configuration
- Agent entry structure (name, source, target) if applicable
- Source file existence verification
- Target download path validity
- Proper indentation and nesting
- No sensitive information included
- Consistency with existing YAML files in repository
- Adequacy for index.yaml structure if updating agents
- Relevancy to repository documentation categories
"""

# Auto-review settings
auto_review = true
enable_auto_approval = false  # Set to true for auto-approval in trusted scenarios
