name: 'Create Pull Request'
description: 'A GitHub Action to create pull requests using peter-evans/create-pull-request'
author: 'FreeMarketamilitia'
branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  token:
    description: 'GitHub token'
    required: true
  path:
    description: 'Relative path to the repository'
    required: true
  branch:
    description: 'The branch to create for the pull request'
    required: false
    default: 'create-pull-request'
  base:
    description: 'The branch to create the pull request against'
    required: false
    default: 'main'
  title:
    description: 'The title of the pull request'
    required: false
    default: 'Automated Pull Request'
  body:
    description: 'The body of the pull request'
    required: false
    default: 'This PR was created automatically'
  committer:
    description: 'The name of the committer'
    required: false
    default: 'github-actions[bot]'
  commit-email:
    description: 'The email of the committer'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  labels:
    description: 'Comma-separated list of labels to apply to the pull request'
    required: false
  delete-branch:
    description: 'Whether to delete the branch after merging the pull request'
    required: false
    default: 'false'
  commit-message:
    description: 'Commit message for the pull request branch'
    required: false
    default: 'Auto commit for PR'

outputs:
  pull-request-number:
    description: 'The number of the created pull request'
  pull-request-url:
    description: 'The URL of the created pull request'

runs:
  using: 'composite'
  steps:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.8
      with:
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        branch: ${{ inputs.branch }}
        base: ${{ inputs.base }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        committer: ${{ inputs.committer }}
        commit-email: ${{ inputs.commit-email }}
        labels: ${{ inputs.labels }}
        delete-branch: ${{ inputs.delete-branch }}
        commit-message: ${{ inputs.commit-message }}
