name: Auto Validate and Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && !github.event.pull_request.merged
    permissions:
      contents: read
      pull-requests: read
    outputs:
      validation-passed: ${{ steps.validation.outputs.result }}
      errors: ${{ steps.validation.outputs.errors }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Validate repository
        id: validation
        continue-on-error: true
        run: |
          echo "🔍 Running repository validation..."
          ERRORS=$(python .github/scripts/validate_index.py)
          echo "errors=$ERRORS" >> $GITHUB_OUTPUT
          if [ $? -eq 0 ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
        shell: bash

      - name: Post validation errors to PR
        if: needs.validate.outputs.validation-passed == 'false'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **Validation failed for this PR** ⚠️

            ```text
            ${{ steps.validation.outputs.errors }}
            ```

  auto-merge:
    needs: validate
    if: |
      needs.validate.outputs.validation-passed == 'true' &&
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      github.event.pull_request.draft == false &&
      !github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Auto merge pull request
        run: |
          echo "🚀 Merging PR #${{ github.event.pull_request.number }}..."
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch=false
          echo "✅ Successfully merged PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: auto-merge
    if: needs.auto-merge.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup merged branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "main" ]; then
            echo "🧹 Cleaning up merged branch: ${{ github.event.pull_request.head.ref }}"
            git push origin --delete "${{ github.event.pull_request.head.ref }}" || echo "Branch already deleted or deletion not permitted"
